### ISSUE TITLE
Make the address "gama-platform.org" stick

### ISSUE THREAD

**Issue by AlexisDrogoul** [mazarsju/gama_doc_17#41]
When typing "gama-platform.org" in a browser, it redirects the user to http://vps226121.ovh.net, which is not completely sexy and informative.

A solution could be to implement this on the website: http://stackoverflow.com/questions/16009901/redirect-to-other-domain-but-keep-typed-domain

**Comment by mazarsju** [comment]
Here is the message of Nhan : "tu pourrais demander Alexis de créer un "A record" et indiquer DNS de "hostname" : gama-plateform.org à l'adresse 51.255.46.42. J'ai configuré dans le server pour attendre ce changement.".

**Comment by langthang** [comment]
The current configuration on server nginx is waiting for an address record from the sub-domain [empty] to the destination 51.255.46.42, not an redirect record to the address http://vps226121.ovh.net. There are two solutions:
The first solution is changing the destination of sub-domain [empty] to the destination 51.255.46.42 instead of http://vps226121.ovh.net. That also requires changing the type of record (something is different from directe(permanente) in french). By this way, the destination of others redirections needs to be changed from http://vps226121.ovh.net/...  to http://gama-platform.org/....
The second solution is to create a proxy on server nginx where the website is locating to redirect http://vps226121.ovh.net to http://gama-platform.org. This one is simple to do but a proxy makes it a little bit not natural and a little bit slower.

**Comment by hqnghi88** [comment]
Salut,
Pouvez vous tester https://www.google.com/search?q=gama+platform&ie=utf-8&oe=utf-8 s'il reste encore des liens 51.xxx ou vpsxxxxx

**Comment by hqnghi88** [comment]
Hi all,
Could you please test the search on google and the website if there still have the links 51.xxx or vpsxxx

**Comment by AlexisDrogoul** [comment]
Hi Nghi,

It works very well. Congrats ! However, there is still a problem (actually a new problem): now, navigating on the site does not provide any individual links (links towards specific pages, etc.). And it is a real problem as we need to point to them (or to reference these individual pages, for example in issue reports...)

Cheers
Alexis

**Comment by hqnghi88** [comment]
Dear Alexis,
I just have done the config as Nhan said. AFAIK, this way of hiding the individual links is a style of web developping, the address bar always show the original site. But yes, it is important to have something like
http://gama-platform.org/tutorials#LearnGAMLStepByStep to report in the issues. I exploit then the solution with Nhan.
Cheers.

**Comment by langthang** [comment]
Hi Nghi,
Thank you, it works btw. Could you please take a snapshot of your DNS config? Send it to me via email. I guess sth is wrong with the type of record you picked because gamawsdev.langthang.me works well.
Cheers.

**Comment by hqnghi88** [comment]
Hi Nhan, 
Sorry, I did not get the notification on this github. Here is the snapshot.
Cheers.
![untitled](https://cloud.githubusercontent.com/assets/6105384/16444561/c5a83ca4-3e08-11e6-95aa-a21752567e76.png)

**Comment by mazarsju** [comment]
Moved to https://github.com/gama-platform/gama.doc/issues/15
